kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: python:2.7
  SourceLocation: ./
  SourceType: local
  Ports:
  - "36000"
  Application: app
  Project: multicast-demo
  Name: producer
